title: Fehlhaber Consulting
description: Accelerating the Cloud & DevOps journey of teams!

baseurl: "" 
url: "https://fehlhaberconsulting.se"
github_username:  kejne
show_excerpts: true

theme: minima
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
  - jekyll-target-blank
  - jekyll-sitemap
